

name: CI/CD
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        
        - name: Setup Maven
          uses: stCarolas/setup-maven@v4.2
          with:
            maven-version: 3.6.0
        
        - name: Maven build
          run: |
              mvn --version
              mvn clean package
        - name: Docker build
          run: docker build --tag dineshkumardevops/hello-world-github-action .
              
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Docker push
          run: docker push  dineshkumardevops/hello-world-github-action
          - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker rm -f hello-world-dev || true
            docker run --name hello-world-dev -d -p 9003:8080 dineshkumardevops/hello-world-github-actions:latest


